# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-22 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50)),
                ('region_url', models.URLField()),
                ('username', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=100)),
            ],
        ),
    ]
