# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZabbixUser',
            new_name='Region',
        ),
    ]
